spring:
  application:
    name: logistic-ops-simple

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # Konfiguracja dla plików statycznych
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      cache:
        cachecontrol:
          no-cache: true
          no-store: true

  # Thymeleaf dla navigation.html
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: UTF-8

# API Keys

api:
  google-maps:
    key: AIzaSyDlcNrZHl85TDrudlFC2HbxFUtg4wQvtKc  # Zastąp prawdziwym kluczem
    enabled: true
    base-url: https://maps.googleapis.com/maps/api
  here-maps:
    key: Gf-TtmVV8nyo6-9tc6QYw4twU2cVA-jE58SxM2jw3po  # Zastąp prawdziwym kluczem
    enabled: true
    base-url: https://router.hereapi.com/v8
# JWT
jwt:
  secret: mySecretKey1234567890abcdefghijklmnopqrstuvwxyz123456789012345678901234567890
  expiration: 86400000

# Server
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

# Logging
logging:
  level:
    root: INFO
    com.military.applogistic: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"